# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170819_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=250)),
                ('question', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='code',
        ),
    ]
