# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_main'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='main',
            new_name='homepage',
        ),
    ]
